// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC7c61ac9DecodeGithubComIlyashestopalovGoMusthaveShortenerTplInternalAppModels(in *jlexer.Lexer, out *APIShortenURL) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "url":
			out.URL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC7c61ac9EncodeGithubComIlyashestopalovGoMusthaveShortenerTplInternalAppModels(out *jwriter.Writer, in APIShortenURL) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v APIShortenURL) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC7c61ac9EncodeGithubComIlyashestopalovGoMusthaveShortenerTplInternalAppModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v APIShortenURL) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC7c61ac9EncodeGithubComIlyashestopalovGoMusthaveShortenerTplInternalAppModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *APIShortenURL) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC7c61ac9DecodeGithubComIlyashestopalovGoMusthaveShortenerTplInternalAppModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *APIShortenURL) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC7c61ac9DecodeGithubComIlyashestopalovGoMusthaveShortenerTplInternalAppModels(l, v)
}
